#所有请求都经过网关设置端口为80端口
server:
  port: 80
#微服务的名称
spring:
  application:
    name: bbt-gateway
eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://bbt:bbt@localhost:8001/register/eureka/
zuul:
  routes:
    bbt-auth:
      #已/auth开头的所有请求都会转到bbt-auth服务
      path: /auth/**
      serviceId: bbt-auth
      #不过滤请求头信息
      sensitiveHeaders: "*"
  #开启重试机制
  retryable: true
  #关闭所有的默认配置规则
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true


